### ISSUE TITLE
Test GeoSearch in Community Profiles

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/dockerfiles#2]
This should just be a drop-in replacement in the frontend.

**Comment by andycochran** [comment]
- made a new branch `geosearch-integration`
- swapped GeoSearch in for Mapzen Search
- geocodes are returning, but only appear in dropdown if they're an exact string match — e.g. `101 WEST 23 STREET` displays but `101 WEST 23rd STREET` does not. 
- clicking results in the dropdown does not navigate to the CD

Reassigning…
