### ISSUE TITLE
Docker container logs filling all disk space

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/dockerfiles#6]
Docker 1.8 has a log rotation option:
```
--log-opt max-size=50m 
```
https://stackoverflow.com/questions/31829587/docker-container-logs-taking-all-my-disk-space/32091923#32091923

**Comment by afeld** [comment]
Closed in https://github.com/NYCPlanning/labs-infrastructure/commit/1f299882b507fc80f11da0c701123957774fd0b2.
